name: cwas
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - attrs=21.4.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - click=8.0.3
  - cyrus-sasl=2.1.27
  - htslib=1.14
  - icu=69.1
  - iniconfig=1.1.1
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgcc=4.8.5
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libntlm=1.4
  - libopenblas=0.3.18
  - libprotobuf=3.19.4
  - libssh2=1.10.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - lz4-c=1.9.3
  - mysql=8.0.28
  - mysql-client=8.0.28
  - mysql-common=8.0.28
  - mysql-connector-c=6.1.11
  - mysql-devel=8.0.28
  - mysql-libs=8.0.28
  - mysql-server=8.0.28
  - ncurses=6.3
  - numpy=1.22.2
  - openssl=1.1.1l
  - packaging=21.3
  - pandas=1.4.1
  - perl=5.26.2
  - perl-bio-bigfile=1.07
  - perl-bioperl=1.6.924
  - perl-dbd-mysql=4.046
  - perl-dbi=1.642
  - perl-io-string=1.08
  - perl-set-intervaltree=0.12
  - perl-threaded=5.32.1
  - perl-yaml=1.29
  - pip=22.0.3
  - pluggy=1.0.0
  - py=1.11.0
  - pyparsing=3.0.7
  - pysam=0.16.0.1
  - pytest=7.0.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-dotenv=0.19.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1
  - scipy=1.8.0
  - setuptools=60.9.0
  - six=1.16.0
  - sqlite=3.37.0
  - tabix=1.11
  - tk=8.6.11
  - tomli=2.0.1
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.5.2
