name: cwas
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - tqdm
  - pysam=0.18.0
  - tabix
  - pyyaml
  - python-dotenv
  - pytest
  - perl
  - perl-dbi
  - perl-dbd-mysql
  - perl-set-intervaltree
  - perl-bio-bigfile
  - perl-bio-db-hts
  - perl-test-warnings
  - perl-try-tiny
  - perl-list-moreutils
  - perl-dbd-sqlite
