name: cwas
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - attrs=21.4.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.8
  - click=8.0.3
  - curl=7.81.0
  - htslib=1.14
  - iniconfig=1.1.1
  - krb5=1.19.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.81.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=3.0.0
  - libgfortran5=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.18
  - libssh2=1.10.0
  - libzlib=1.2.11
  - llvm-openmp=13.0.1
  - ncurses=6.3
  - numpy=1.22.2
  - openssl=3.0.0
  - packaging=21.3
  - pandas=1.4.1
  - pip=22.0.3
  - pluggy=1.0.0
  - py=1.11.0
  - pyparsing=3.0.7
  - pysam=0.16.0.1
  - pytest=7.0.1
  - python=3.9.10
  - python-dateutil=2.8.2
  - python-dotenv=0.19.2
  - python_abi=3.9
  - pytz=2021.3
  - pyyaml=6.0
  - readline=8.1
  - scipy=1.8.0
  - setuptools=60.9.0
  - six=1.16.0
  - sqlite=3.37.0
  - tabix=1.11
  - tk=8.6.11
  - tomli=2.0.1
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
